version: '3'
services:
    server:
        image: mysql:latest
        container_name: server
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: server
            MYSQL_ROOT_PASSWORD: secret

    client:
        image: mysql:latest
        container_name: client
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: client
            MYSQL_ROOT_PASSWORD: secret

